### ISSUE TITLE
Support all browsers for our extension

### ISSUE THREAD

**Issue by posix4e** [posix4e/puppet#12]
Currently we only support IOS. Let's support chrome. Let's provide tests,ci and cd

**Comment by kernel-loophole** [comment]
hi there ,this is zulqarnain from replit .I have some question about it .
What are the key features or functionalities that you would like to ensure work seamlessly in the Chrome version of the extension?
Are there specific aspects of the JavaScript codebase that need to be adapted for Chrome compatibility? Are there any iOS-specific features that need to be adjusted?
Looking forward to discuss more .

**Comment by posix4e** [comment]
I don’t think we should worry about breaking functionality. If it does break we should add a failing  unit test . The existing logic is very trivial and only consists of a few html and js files. The real goal behind this issue is making a first stab on a working test and deploy framework

**Comment by kernel-loophole** [comment]
That's great.when you want this ready.

**Comment by posix4e** [comment]
When you can

**Comment by kernel-loophole** [comment]
2 weeks

**Comment by posix4e** [comment]
OkSent from my iPhoneOn Aug 19, 2023, at 22:19, Zulqarnain ***@***.***> wrote:﻿
2 weeks

**Comment by kernel-loophole** [comment]
great ,so i am sending proposal on replit .

**Comment by kernel-loophole** [comment]
can you accept my work on replit .

**Comment by posix4e** [comment]
You did tests, ci but not cd. You need to publish the extension as a zip file whenever a tag release event happens. Should be pretty easy now that we have ci working

**Comment by kernel-loophole** [comment]
so should i publish this to Chrome Web Store?

**Comment by posix4e** [comment]
If it’s easy enough, but that’s not required. What is required is a zip
file being published on the tags/releases. Check the other examples in the
.github repo that we do to publish apk files

**Comment by kernel-loophole** [comment]
```

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run:
          git push https://posix4e:$HF_TOKEN@huggingface.co/spaces/posix4e/puppet main

```
are you talking about this one .
